### ISSUE TITLE
use Bootstrap

### ISSUE THREAD

**Issue by notghettolenny** [samramires/my-first-website#1]
instead of styling with css, use Bootstrap to predefine button styles
<button type="button" class="btn btn-primary">Primary</button>
<button type="button" class="btn btn-secondary">Secondary</button>
<button type="button" class="btn btn-success">Success</button>
<button type="button" class="btn btn-danger">Danger</button>
<button type="button" class="btn btn-warning">Warning</button>
<button type="button" class="btn btn-info">Info</button>
<button type="button" class="btn btn-light">Light</button>
<button type="button" class="btn btn-dark">Dark</button>

<button type="button" class="btn btn-link">Link</button>

**Comment by samramires** [comment]
Thanks
